query TasksQuery($cloudId: ID!) {
  jira {
    issueSearchStable(
      cloudId: $cloudId
      issueSearchInput: {
        jql: "project = DEV and status in (\"To Do\", \"In Progress\") ORDER BY priority DESC, createdDate ASC"
      }
    ) {
      edges {
        node {
          webUrl
          key
          fieldsById(ids: ["summary", "priority"]) {
            edges {
              node {
                name
                fieldId
                description
                type
                __typename
                ... on JiraSingleLineTextField {
                  text
                }
                ... on JiraPriorityField {
                  priority {
                    name
                    color
                    iconUrl
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
